name: eShopOnWeb Build and Test

on: [push, workflow_dispatch]

env:
  RESOURCE_GROUP: rg-prac
  WEBAPP_NAME: eshoponweb-webapp-free

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build ./eShopOnWeb.sln -c Release

      - name: Test
        run: dotnet test ./eShopOnWeb.sln -c Release --no-build

      - name: Publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{ env.DOTNET_ROOT }}/myapp
          cd ${{ env.DOTNET_ROOT }}/myapp && zip -r ../app.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-zip
          path: ${{ env.DOTNET_ROOT }}/app.zip

  deploy:
    needs: buildandtest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-zip
          path: .

      # 発行プロファイル方式（Azure/login不要）
      - name: Deploy with publish profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./app.zip
